# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: condense-json
  version: "0.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/condense_json-${{ version }}.tar.gz
  sha256: 25fe8d434fdafd849e8d98f21a3e18f96ae2d6dbc2c17565f29e4843d039d2bc

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - condense_json
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Python function for condensing JSON using replacement strings
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/simonw/condense-json

extra:
  recipe-maintainers:
    - rxm7706
